site_name: Replica
site_url: https://madstudioroblox.github.io/Replica
repo_name: MadStudioRoblox/Replica
repo_url: https://github.com/MadStudioRoblox/Replica

theme:
  icon:
    logo: material/lan-connect
  name: material
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep purple
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
      accent: purple 

nav:
  - Home: index.md
  - API: api/index.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences